package Model;
// Generated May 13, 2020 10:29:22 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Book generated by hbm2java
 */
public class Book  implements java.io.Serializable {


     private Integer id;
     private Bookcategory bookcategory;
     private String title;
     private String publishinghouse;
     private Date publicationdate;
     private String author;
     private int pages;
     private Set checkinouts = new HashSet(0);

    public Book() {
    }

	
    public Book(Bookcategory bookcategory, String title, String publishinghouse, Date publicationdate, String author, int pages) {
        this.bookcategory = bookcategory;
        this.title = title;
        this.publishinghouse = publishinghouse;
        this.publicationdate = publicationdate;
        this.author = author;
        this.pages = pages;
    }
    public Book(Bookcategory bookcategory, String title, String publishinghouse, Date publicationdate, String author, int pages, Set checkinouts) {
       this.bookcategory = bookcategory;
       this.title = title;
       this.publishinghouse = publishinghouse;
       this.publicationdate = publicationdate;
       this.author = author;
       this.pages = pages;
       this.checkinouts = checkinouts;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Bookcategory getBookcategory() {
        return this.bookcategory;
    }
    
    public void setBookcategory(Bookcategory bookcategory) {
        this.bookcategory = bookcategory;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public String getPublishinghouse() {
        return this.publishinghouse;
    }
    
    public void setPublishinghouse(String publishinghouse) {
        this.publishinghouse = publishinghouse;
    }
    public Date getPublicationdate() {
        return this.publicationdate;
    }
    
    public void setPublicationdate(Date publicationdate) {
        this.publicationdate = publicationdate;
    }
    public String getAuthor() {
        return this.author;
    }
    
    public void setAuthor(String author) {
        this.author = author;
    }
    public int getPages() {
        return this.pages;
    }
    
    public void setPages(int pages) {
        this.pages = pages;
    }
    public Set getCheckinouts() {
        return this.checkinouts;
    }
    
    public void setCheckinouts(Set checkinouts) {
        this.checkinouts = checkinouts;
    }




}


