package Model;
// Generated May 13, 2020 10:29:22 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Bookcategory generated by hbm2java
 */
public class Bookcategory  implements java.io.Serializable {


     private Integer categoryId;
     private String categoryName;
     private Set books = new HashSet(0);

    public Bookcategory() {
    }

	
    public Bookcategory(String categoryName) {
        this.categoryName = categoryName;
    }
    public Bookcategory(String categoryName, Set books) {
       this.categoryName = categoryName;
       this.books = books;
    }
   
    public Integer getCategoryId() {
        return this.categoryId;
    }
    
    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }
    public String getCategoryName() {
        return this.categoryName;
    }
    
    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName;
    }
    public Set getBooks() {
        return this.books;
    }
    
    public void setBooks(Set books) {
        this.books = books;
    }




}


